---
title: "Expected Runs"
author: "Jack Banks"
date: "6/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggcorrplot)
library(MASS)
```

# Loading Data

```{r}
Full = read_excel("C:/Users/My Laptop/OneDrive/Desktop/Battle Creek/Reshaped Standings/Expected Runs Historical.xlsx")

perGame = read_excel("C:/Users/My Laptop/OneDrive/Desktop/Battle Creek/Reshaped Standings/Expected Runs Historical.xlsx", sheet = "Per Game")

perGame <- {
  perGame %>% 
    filter(G > 26) %>% 
    filter(Team != "TOTALS")
}

no2020 <- {
  perGame %>% 
    filter(Year != 2020)
}



```


# Initial Model

```{r}

model = lm(R ~ HR + BB + SB + AVG, data = perGame)
summary(model)

model_peta = lm(HPR ~ OBP + SLG + ISO, data = perGame)
summary(model_peta)

model_OPS = lm(R ~ OPS, data = perGame)
summary(model_OPS)

model_RC = lm(R ~ RC + SB, data = perGame)
summary(model_RC)
```

```{r}

model_full = lm(R ~ . - Team - Year - Label - HPR, data = perGame)
model_AIC <- stepAIC(model_full, direction = "both", trace = FALSE)
summary(model_AIC)

simple_full = lm(R ~ H + HR + K + BB + SB + CS + AVG + OBP + SLG + ISO + SECA,
                 data = perGame)
simple_AIC <- stepAIC(simple_full, direction = "both", trace = FALSE)
summary(simple_AIC)

final <- lm(R ~ H + SECA + OBP , data = perGame)
summary(final)


tb <- lm(R ~ TB, data = perGame)
summary(tb)
```


#Predicted vs. Actual

```{r}

plot(fitted(model_AIC) ~ perGame$R, main = "Best Stat Model")
abline(0,1)

plot(fitted(simple_AIC) ~ perGame$R, main = "Best Logical Model")
abline(0,1)

plot(fitted(final) ~ perGame$R, main = "Best Model")
abline(0,1)
#text(fitted(hope) ~ perGame$R, labels = perGame$Label)



```

# Runs Allowed

```{r}

#Full = read_excel("C:/Users/My Laptop/OneDrive/Desktop/Battle Creek/Reshaped Standings/Expected Runs Historical.xlsx")

RA = read_excel("C:/Users/My Laptop/OneDrive/Desktop/Battle Creek/Reshaped Standings/Expected Runs Historical.xlsx", sheet = "RA Per Game")

RA <- {
  RA %>% 
    filter(G > 26) %>% 
    filter(Team != "TOTALS")
}



```

#models

```{r}

fip <- lm(R ~ FIP, data = RA)
summary(fip)


full <- lm(R ~ . - Team - Year - Label - G - ERA, data = RA)
best <- stepAIC(full, direction = "both", trace = FALSE)
summary(best)

finalRA <- lm(R ~ K + HR + WHIP,
              data = RA)
summary(finalRA)

bbk <- lm(R ~ `BB%` + K, data = RA)
summary(bbk)
```

```{r}
plot(fitted(finalRA) ~ RA$R, main = "Best Model")
abline(0,1)
```
#Ind Hitter
```{r}



```

